In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4240, 9993, 5951, 4223],
 [4240, 9993, 5951, 4167],
 [4240, 4624, 5951, 8952],
 [8775, 3512, 6101, 1050, 4468],
 [8775, 3512, 6101, 1050, 8658],
 [7745, 4240, 5844, 5951, 5139],
 [1904, 109, 7111, 1050]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4240 9993 5951 4223]
 [   0    0    0    0 4240 9993 5951 4167]
 [   0    0    0    0 4240 4624 5951 8952]
 [   0    0    0 8775 3512 6101 1050 4468]
 [   0    0    0 8775 3512 6101 1050 8658]
 [   0    0    0 7745 4240 5844 5951 5139]
 [   0    0    0    0 1904  109 7111 1050]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 202ms/step


array([[[-0.04495381,  0.03059191, -0.02178992, -0.02973771,
         -0.04731481, -0.01079429,  0.00670796, -0.0263666 ,
         -0.02791666,  0.00174278],
        [-0.04495381,  0.03059191, -0.02178992, -0.02973771,
         -0.04731481, -0.01079429,  0.00670796, -0.0263666 ,
         -0.02791666,  0.00174278],
        [-0.04495381,  0.03059191, -0.02178992, -0.02973771,
         -0.04731481, -0.01079429,  0.00670796, -0.0263666 ,
         -0.02791666,  0.00174278],
        [-0.04495381,  0.03059191, -0.02178992, -0.02973771,
         -0.04731481, -0.01079429,  0.00670796, -0.0263666 ,
         -0.02791666,  0.00174278],
        [ 0.01959955, -0.00475729, -0.03993898,  0.03390009,
          0.03022726,  0.02223623,  0.01403708, -0.02332845,
         -0.04676143, -0.02490494],
        [ 0.02290884,  0.02592976,  0.00028157, -0.03833151,
          0.03666767,  0.03592426,  0.03548444,  0.04395564,
          0.0229691 ,  0.01404308],
        [-0.01292636,  0.00203956, -0.004733  ,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4240, 9993, 5951, 4223])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 62ms/step


array([[-0.04495381,  0.03059191, -0.02178992, -0.02973771, -0.04731481,
        -0.01079429,  0.00670796, -0.0263666 , -0.02791666,  0.00174278],
       [-0.04495381,  0.03059191, -0.02178992, -0.02973771, -0.04731481,
        -0.01079429,  0.00670796, -0.0263666 , -0.02791666,  0.00174278],
       [-0.04495381,  0.03059191, -0.02178992, -0.02973771, -0.04731481,
        -0.01079429,  0.00670796, -0.0263666 , -0.02791666,  0.00174278],
       [-0.04495381,  0.03059191, -0.02178992, -0.02973771, -0.04731481,
        -0.01079429,  0.00670796, -0.0263666 , -0.02791666,  0.00174278],
       [ 0.01959955, -0.00475729, -0.03993898,  0.03390009,  0.03022726,
         0.02223623,  0.01403708, -0.02332845, -0.04676143, -0.02490494],
       [ 0.02290884,  0.02592976,  0.00028157, -0.03833151,  0.03666767,
         0.03592426,  0.03548444,  0.04395564,  0.0229691 ,  0.01404308],
       [-0.01292636,  0.00203956, -0.004733  ,  0.01036271, -0.04388766,
         0.02309066, -0.04236869,  0.02927723